### PR TITLE
compareSpectriPy function

### PR DESCRIPTION
**Pull request by chufz**
Unsure if this is the desired way to do it, but the way I was capable of...
Depending on the function parameters it generates a string named `pycommand` and then runs it with  `reticulate::pycommand`.
Decide or advise how to do better.
For now, I included 4 different spectra comparission functions

### CODE REVIEW

**Comment by hechth** [comment]
So this is trying to solve #11 ?

**Review by jorainer — COMMENTED** [review]
Thanks Caro! Looks like a good start for me. There are some minor coding style issues, but I can take care of that later.

One thing that I would however suggest is to make `compareSpectriPy` a method instead of a function and to have `CosineGreedyParam`, `CosineHungarianParam` etc parameter objects to select the algorithm and configure it. That way we would avoid having parameters in the function definitions that are only used by one of the algorithms. If you are not familiar with S4 method definitions etc I could take care of that, take your PR as a start and refactor the functions. Would that be OK for you and the others?

**Comment by chufz** [comment]
> t I would however suggest is to make `compareSpectriPy` a method instead of a function and to have `CosineGreedyParam`, `CosineHungarianParam` etc parameter objects to select the algorithm and configure it. That way we would avoid having parameters in the function definitions that are only used by one of the algorithms. If you are not familiar with S4 method definitions etc I could take care of that, take your PR as a start and refactor the functions. Would that be OK for you and the others?

Sounds good, yes I am not that familiar with S4 yet, but curious how that will look like

**Comment by jorainer** [comment]
OK, then I will merge work on it and explain.

**Pull request merged**
